# Generated by Django 3.1.1 on 2020-09-10 21:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crud_project', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstname', models.CharField(max_length=15)),
                ('password', models.CharField(max_length=15)),
                ('email', models.CharField(max_length=64)),
                ('lastname', models.CharField(max_length=15)),
            ],
        ),
        migrations.DeleteModel(
            name='Users',
        ),
    ]
